/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"

#include <string.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Number of bytes to be sent through SPI */
#define MESSAGE_SIZE_BYTES                2U

/* Message's preamble */
#define MESSAGE_PREAMBLE                  0xA5

/* Message's initial data value */
#define MESSAGE_INITIAL_VALUE             0x00

/* Delay between each SPI transfer in ms */
#define DELAY_BETWEEN_TRANSFER_MS         10U

/* Number of messages per test */
#define MESSAGES_PER_TEST                 100U

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initSmartIOencoder(void);
void initSmartIOdecoder(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: initSmartIOencoder
 * Summary:
 *  Initialize and enable SPI master and Smart I/O port for Manchester encoding.
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
void initSmartIOencoder(void)
{
    cy_stc_scb_spi_context_t spiContextMaster;

    /* Initialize SPI Master */
    if (CY_SCB_SPI_SUCCESS != Cy_SCB_SPI_Init(SPI_MASTER_HW, &SPI_MASTER_config, &spiContextMaster))
    {
        CY_ASSERT(0);
    }

    /* Enable SPI block */
    Cy_SCB_SPI_Enable(SPI_MASTER_HW);

    /* Initialize Smart I/O Manchester encoding block */
    if (CY_SMARTIO_SUCCESS != Cy_SmartIO_Init(SMARTIO_MANCHESTER_ENCODING_HW, &SMARTIO_MANCHESTER_ENCODING_config))
    {
        CY_ASSERT(0);
    }

    /* Enable Smart I/O block */
    Cy_SmartIO_Enable(SMARTIO_MANCHESTER_ENCODING_HW);
}

/**********************************************************************************************************************
 * Function Name: initSmartIOdecoder
 * Summary:
 *  Initialize SPI slave and Smart I/O port for Manchester decoding.
 *  Additionally, initialize TCPWM counters that are used for decoding Manchester data.
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
void initSmartIOdecoder(void)
{
    cy_stc_scb_spi_context_t spiContextSlave;

    /* Initialize SPI Slave */
    if (CY_SCB_SPI_SUCCESS != Cy_SCB_SPI_Init(SPI_SLAVE_HW, &SPI_SLAVE_config, &spiContextSlave))
    {
        CY_ASSERT(0);
    }

    /* Set SELECT1 as active slave select */
    Cy_SCB_SPI_SetActiveSlaveSelect(SPI_SLAVE_HW, CY_SCB_SPI_SLAVE_SELECT1);

    /* Enable SPI block */
    Cy_SCB_SPI_Enable(SPI_SLAVE_HW);

    /* Initialize Smart IO Manchester decoding block */
    if (CY_SMARTIO_SUCCESS != Cy_SmartIO_Init(SMARTIO_MANCHESTER_DECODING_HW, &SMARTIO_MANCHESTER_DECODING_config))
    {
        CY_ASSERT(0);
    }

    /* Enable Smart I/O block */
    Cy_SmartIO_Enable(SMARTIO_MANCHESTER_DECODING_HW);

    /* Initialize PWM signal for RS flipflop's 'reset' input */
    if (CY_TCPWM_SUCCESS != Cy_TCPWM_PWM_Init(TCPWM_FLIPFLOP_RESET_HW, TCPWM_FLIPFLOP_RESET_NUM,
            &TCPWM_FLIPFLOP_RESET_config))
    {
        CY_ASSERT(0);
    }

    /* Enable counter for PWM operation */
    Cy_TCPWM_PWM_Enable(TCPWM_FLIPFLOP_RESET_HW, TCPWM_FLIPFLOP_RESET_NUM);

    /* Initialize PWM signal for SPI slave clock */
    if (CY_TCPWM_SUCCESS != Cy_TCPWM_PWM_Init(TCPWM_SPI_CLK_IN_HW, TCPWM_SPI_CLK_IN_NUM, &TCPWM_SPI_CLK_IN_config))
    {
        CY_ASSERT(0);
    }

    /* Enable counter for PWM operation */
    Cy_TCPWM_PWM_Enable(TCPWM_SPI_CLK_IN_HW, TCPWM_SPI_CLK_IN_NUM);

    /* Trigger a single shot to reset the RS flipflop in the beginning */
    Cy_TCPWM_TriggerStart_Single(TCPWM_FLIPFLOP_RESET_HW, TCPWM_FLIPFLOP_RESET_NUM);
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t result;

    /* Variables to send and receive data through SPI */
    uint8_t sendBytes[MESSAGE_SIZE_BYTES];
    uint8_t receiveBytes[MESSAGE_SIZE_BYTES];

    /* Variables to store message data and keep a count of messages received by SPI block */
    uint8_t messageData = 0;
    uint32_t messageCount = 0;

    /* Variables to track the success rate of Manchester decoding */
    uint32_t successCount = 0;
    uint32_t failureCount = 0;

#if defined (CY_DEVICE_SECURE)
    cyhal_wdt_t wdt_obj;

    /* Clear watchdog timer so that it doesn't trigger a reset */
    result = cyhal_wdt_init(&wdt_obj, cyhal_wdt_get_max_timeout_ms());
    CY_ASSERT(CY_RSLT_SUCCESS == result);
    cyhal_wdt_free(&wdt_obj);
#endif

    /* Initialize the device and board peripherals */
    result = cybsp_init();

    /* Board init failed. Stop program execution */
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize retarget-io to use the debug UART port */
    result = cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE);

    /* retarget-io init failed. Stop program execution */
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    initSmartIOencoder();
    initSmartIOdecoder();

    sendBytes[0] = MESSAGE_PREAMBLE;
    sendBytes[1] = MESSAGE_INITIAL_VALUE;

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");
    printf("********************************************************************************\r\n");
    printf("            Manchester Encoding and Decoding Using Smart I/O\r\n");
    printf("********************************************************************************\r\n\r\n");
    printf("Please ensure a jumper wire is connected on the mikroBUS header between\r\n"
           "J11.1 - Manchester_Tx (pin P14.2) and J11.6 - Manchester_Rx (pin P13.1).\r\n\r\n");

    printf("The verification status of Manchester encoding and decoding:\r\n");
    printf("Success: %lu\r\n", successCount);
    printf("Failure: %lu\r\n", failureCount);

    /* Enable global interrupts */
    __enable_irq();

    for (;;)
    {
        /* Send message which is transformed to Manchester encoded Data via Smart I/O */
        Cy_SCB_SPI_WriteArray(SPI_MASTER_HW, sendBytes, MESSAGE_SIZE_BYTES);

        /* Wait until the required decoded bytes are received */
        while(Cy_SCB_SPI_GetNumInRxFifo(SPI_SLAVE_HW) < MESSAGE_SIZE_BYTES)
        {
        }

        /* Read the Manchester decoded data */
        Cy_SCB_SPI_ReadArray(SPI_SLAVE_HW, receiveBytes, MESSAGE_SIZE_BYTES);

        /* Compare if the sent data is same as the received data.
         * This is to verify the correctness of Manchester decoding. */
        if (memcmp(sendBytes, receiveBytes, (size_t) MESSAGE_SIZE_BYTES) == 0)
        {
            /* Increment count if decoding was successful */
            successCount++;
        }
        else
        {
            /* Increment count if decoding was unsuccessful */
            failureCount++;
        }

        /* Change second byte for next SPI transmission */
        messageData++;
        sendBytes[1] = messageData;

        /* Keep track of number of messages sent */
        messageCount++;

        /* Display current decoding status after every MESSAGES_PER_TEST samples */
        if ((messageCount % MESSAGES_PER_TEST) == 0)
        {
            /* Move cursor 2 lines above */
            printf("\x1b[2F");
            printf("Success: %lu\r\n", successCount);
            printf("Failure: %lu\r\n", failureCount);
        }

        cyhal_system_delay_ms(DELAY_BETWEEN_TRANSFER_MS);
    }
}
